/*
* Copyright 2023 NXP
* All rights reserved.
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.1
processor: LPC865
package_id: LPC865M201JBD64
mcu_data: ksdk2_0
processor_version: 13.0.0
pin_labels:
- {pin_num: '18', pin_signal: PIO1_1, label: LED_B_P, identifier: LED_B_P}
- {pin_num: '20', pin_signal: PIO1_2, label: LED_B_N, identifier: LED_B_N}
- {pin_num: '29', pin_signal: PIO1_3, label: LED_R_P, identifier: LED_R_P}
- {pin_num: '31', pin_signal: PIO1_4, label: LED_R_N, identifier: LED_R_N}
- {pin_num: '35', pin_signal: PIO1_5, label: LED_G_P, identifier: LED_G_P}
- {pin_num: '38', pin_signal: PIO1_6, label: LED_G_N, identifier: LED_G_N}
- {pin_num: '46', pin_signal: PIO0_6/ADC_1/ACMPVREF, label: ADC_LED_G, identifier: ADC_LED_G}
- {pin_num: '51', pin_signal: PIO0_23/ADC_3/ACMP_I4, label: ADC_LED_B, identifier: ADC_LED_B}
- {pin_num: '61', pin_signal: PIO0_18/ADC_8, label: ADC_ALS, identifier: ADC_ALS}
- {pin_num: '63', pin_signal: PIO0_17/ADC_9, label: ADC_NTC, identifier: ADC_NTC}
- {pin_num: '2', pin_signal: PIO0_13/ADC_10, label: ADC_POT, identifier: ADC_POT}
- {pin_num: '49', pin_signal: PIO0_14/ACMP_I3/ADC_2, label: ADC_LED_R, identifier: ADC_LED_R}
- {pin_num: '60', pin_signal: PIO0_19/ADC_7, label: DBG0, identifier: DBG0}
- {pin_num: '58', pin_signal: PIO0_20/ADC_6, label: DBG1, identifier: DBG1}
- {pin_num: '30', pin_signal: PIO0_15, label: TX, identifier: DALI_RX;RX;TX}
- {pin_num: '19', pin_signal: PIO0_16, label: RX, identifier: DALI_TX;TX;RX}
- {pin_num: '6', pin_signal: PIO0_4/ADC_11, label: BTN_USR, identifier: BTN_USR}
- {pin_num: '57', pin_signal: PIO0_21/ADC_5, label: DBG2, identifier: DBG2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iocon.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitDbgUARTPins();
    BOARD_InitSYSPins();
    BOARD_InitI2CPins();
    BOARD_InitDbgPins();
    BOARD_InitDALIPins();
    BOARD_InitBTNPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDbgUARTPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '27', peripheral: USART0, signal: TXD, pin_signal: PIO0_25}
  - {pin_num: '28', peripheral: USART0, signal: RXD, pin_signal: PIO0_24}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDbgUARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitDbgUARTPins(void)
{
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);

    /* USART0_TXD connect to P0_25 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_25);

    /* USART0_RXD connect to P0_24 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_24);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSYSPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '33', peripheral: SYSCON, signal: XTALOUT, pin_signal: PIO0_9/XTALOUT}
  - {pin_num: '34', peripheral: SYSCON, signal: XTALIN, pin_signal: PIO0_8/XTALIN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSYSPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitSYSPins(void)
{
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);

    /* XTALIN connect to P0_8 */
    SWM_SetFixedPinSelect(SWM0, kSWM_XTALIN, true);

    /* XTALOUT connect to P0_9 */
    SWM_SetFixedPinSelect(SWM0, kSWM_XTALOUT, true);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDPins:
- options: {createDeInit: 'true', callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '18', peripheral: FTM0, signal: 'CH, 0', pin_signal: PIO1_1}
  - {pin_num: '20', peripheral: FTM0, signal: 'CH, 1', pin_signal: PIO1_2}
  - {pin_num: '29', peripheral: FTM0, signal: 'CH, 2', pin_signal: PIO1_3}
  - {pin_num: '31', peripheral: FTM0, signal: 'CH, 3', pin_signal: PIO1_4}
  - {pin_num: '35', peripheral: FTM0, signal: 'CH, 4', pin_signal: PIO1_5}
  - {pin_num: '38', peripheral: FTM0, signal: 'CH, 5', pin_signal: PIO1_6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitLEDPins(void)
{
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);

    /* FTM0_CH0 connect to kSWM_FTM_Selection1 */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH0, kSWM_FTM_Selection1);

    /* FTM0_CH1 connect to kSWM_FTM_Selection1 */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH1, kSWM_FTM_Selection1);

    /* FTM0_CH2 connect to kSWM_FTM_Selection1 */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH2, kSWM_FTM_Selection1);

    /* FTM0_CH3 connect to kSWM_FTM_Selection1 */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH3, kSWM_FTM_Selection1);

    /* FTM0_CH4 connect to kSWM_FTM_Selection1 */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH4, kSWM_FTM_Selection1);

    /* FTM0_CH5 connect to kSWM_FTM_Selection1 */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH5, kSWM_FTM_Selection1);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDPins_deinit
 * Description   : This is a de-initialization function for 'BOARD_InitLEDPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitLEDPins_deinit(void)
{
    /* Enables clock for IOCON.: enable */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);
    /* Enables the clock for the GPIO1 module */
    CLOCK_EnableClock(kCLOCK_Gpio1);

    gpio_pin_config_t LED_B_P_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_1 (pin 18)  */
    GPIO_PinInit(BOARD_INITLEDPINS_DEINIT_LED_B_P_GPIO, BOARD_INITLEDPINS_DEINIT_LED_B_P_PORT, BOARD_INITLEDPINS_DEINIT_LED_B_P_PIN, &LED_B_P_config);

    gpio_pin_config_t LED_B_N_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_2 (pin 20)  */
    GPIO_PinInit(BOARD_INITLEDPINS_DEINIT_LED_B_N_GPIO, BOARD_INITLEDPINS_DEINIT_LED_B_N_PORT, BOARD_INITLEDPINS_DEINIT_LED_B_N_PIN, &LED_B_N_config);

    gpio_pin_config_t LED_R_P_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_3 (pin 29)  */
    GPIO_PinInit(BOARD_INITLEDPINS_DEINIT_LED_R_P_GPIO, BOARD_INITLEDPINS_DEINIT_LED_R_P_PORT, BOARD_INITLEDPINS_DEINIT_LED_R_P_PIN, &LED_R_P_config);

    gpio_pin_config_t LED_R_N_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_4 (pin 31)  */
    GPIO_PinInit(BOARD_INITLEDPINS_DEINIT_LED_R_N_GPIO, BOARD_INITLEDPINS_DEINIT_LED_R_N_PORT, BOARD_INITLEDPINS_DEINIT_LED_R_N_PIN, &LED_R_N_config);

    gpio_pin_config_t LED_G_P_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_5 (pin 35)  */
    GPIO_PinInit(BOARD_INITLEDPINS_DEINIT_LED_G_P_GPIO, BOARD_INITLEDPINS_DEINIT_LED_G_P_PORT, BOARD_INITLEDPINS_DEINIT_LED_G_P_PIN, &LED_G_P_config);

    gpio_pin_config_t LED_G_N_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_6 (pin 38)  */
    GPIO_PinInit(BOARD_INITLEDPINS_DEINIT_LED_G_N_GPIO, BOARD_INITLEDPINS_DEINIT_LED_G_N_PORT, BOARD_INITLEDPINS_DEINIT_LED_G_N_PIN, &LED_G_N_config);

    const uint32_t LED_B_P = (/* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO1 PIN1 (coords: 18) is configured as GPIO, PIO1, 1. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_1, LED_B_P);

    const uint32_t LED_B_N = (/* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO1 PIN2 (coords: 20) is configured as GPIO, PIO1, 2. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_2, LED_B_N);

    const uint32_t LED_R_P = (/* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO1 PIN3 (coords: 29) is configured as GPIO, PIO1, 3. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_3, LED_R_P);

    const uint32_t LED_R_N = (/* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO1 PIN4 (coords: 31) is configured as GPIO, PIO1, 4. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_4, LED_R_N);

    const uint32_t LED_G_P = (/* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO1 PIN5 (coords: 35) is configured as GPIO, PIO1, 5. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_5, LED_G_P);

    const uint32_t LED_G_N = (/* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO1 PIN6 (coords: 38) is configured as GPIO, PIO1, 6. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_6, LED_G_N);

    /* FTM0_CH0 connect to no pin */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH0, kSWM_FTM_Selection3);

    /* FTM0_CH1 connect to no pin */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH1, kSWM_FTM_Selection3);

    /* FTM0_CH2 connect to no pin */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH2, kSWM_FTM_Selection3);

    /* FTM0_CH3 connect to no pin */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH3, kSWM_FTM_Selection3);

    /* FTM0_CH4 connect to no pin */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH4, kSWM_FTM_Selection3);

    /* FTM0_CH5 connect to no pin */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM0_CH5, kSWM_FTM_Selection3);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitADCPins:
- options: {createDeInit: 'true', callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '63', peripheral: ADC0, signal: 'CH, 9', pin_signal: PIO0_17/ADC_9}
  - {pin_num: '49', peripheral: ADC0, signal: 'CH, 2', pin_signal: PIO0_14/ACMP_I3/ADC_2}
  - {pin_num: '46', peripheral: ADC0, signal: 'CH, 1', pin_signal: PIO0_6/ADC_1/ACMPVREF}
  - {pin_num: '51', peripheral: ADC0, signal: 'CH, 3', pin_signal: PIO0_23/ADC_3/ACMP_I4}
  - {pin_num: '2', peripheral: ADC0, signal: 'CH, 10', pin_signal: PIO0_13/ADC_10}
  - {pin_num: '61', peripheral: ADC0, signal: 'CH, 8', pin_signal: PIO0_18/ADC_8}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitADCPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitADCPins(void)
{
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);

    /* ADC_CHN1 connect to P0_6 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN1, true);

    /* ADC_CHN2 connect to P0_14 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN2, true);

    /* ADC_CHN3 connect to P0_23 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN3, true);

    /* ADC_CHN8 connect to P0_18 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN8, true);

    /* ADC_CHN9 connect to P0_17 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN9, true);

    /* ADC_CHN10 connect to P0_13 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN10, true);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitADCPins_deinit
 * Description   : This is a de-initialization function for 'BOARD_InitADCPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitADCPins_deinit(void)
{
    /* Enables clock for IOCON.: enable */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t ADC_LED_G_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_6 (pin 46)  */
    GPIO_PinInit(BOARD_INITADCPINS_DEINIT_ADC_LED_G_GPIO, BOARD_INITADCPINS_DEINIT_ADC_LED_G_PORT, BOARD_INITADCPINS_DEINIT_ADC_LED_G_PIN, &ADC_LED_G_config);

    gpio_pin_config_t ADC_POT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_13 (pin 2)  */
    GPIO_PinInit(BOARD_INITADCPINS_DEINIT_ADC_POT_GPIO, BOARD_INITADCPINS_DEINIT_ADC_POT_PORT, BOARD_INITADCPINS_DEINIT_ADC_POT_PIN, &ADC_POT_config);

    gpio_pin_config_t ADC_LED_R_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_14 (pin 49)  */
    GPIO_PinInit(BOARD_INITADCPINS_DEINIT_ADC_LED_R_GPIO, BOARD_INITADCPINS_DEINIT_ADC_LED_R_PORT, BOARD_INITADCPINS_DEINIT_ADC_LED_R_PIN, &ADC_LED_R_config);

    gpio_pin_config_t ADC_NTC_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_17 (pin 63)  */
    GPIO_PinInit(BOARD_INITADCPINS_DEINIT_ADC_NTC_GPIO, BOARD_INITADCPINS_DEINIT_ADC_NTC_PORT, BOARD_INITADCPINS_DEINIT_ADC_NTC_PIN, &ADC_NTC_config);

    gpio_pin_config_t gpio0_pin0_18 = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_18 (pin 61)  */
    GPIO_PinInit(GPIO, 0U, 18U, &gpio0_pin0_18);

    gpio_pin_config_t ADC_LED_B_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_23 (pin 51)  */
    GPIO_PinInit(BOARD_INITADCPINS_DEINIT_ADC_LED_B_GPIO, BOARD_INITADCPINS_DEINIT_ADC_LED_B_PORT, BOARD_INITADCPINS_DEINIT_ADC_LED_B_PIN, &ADC_LED_B_config);

    const uint32_t ADC_POT = (/* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO0 PIN13 (coords: 2) is configured as GPIO, PIO0, 13. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_13, ADC_POT);

    const uint32_t ADC_LED_R = (/* No addition pin function */
                                IOCON_PIO_MODE_INACT |
                                /* Enable hysteresis */
                                IOCON_PIO_HYS_EN |
                                /* Input not invert */
                                IOCON_PIO_INV_DI |
                                /* Disables Open-drain function */
                                IOCON_PIO_OD_DI |
                                /* Bypass input filter */
                                IOCON_PIO_SMODE_BYPASS |
                                /* IOCONCLKDIV0 */
                                IOCON_PIO_CLKDIV0);
    /* PIO0 PIN14 (coords: 49) is configured as GPIO, PIO0, 14. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_14, ADC_LED_R);

    const uint32_t ADC_NTC = (/* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO0 PIN17 (coords: 63) is configured as GPIO, PIO0, 17. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_17, ADC_NTC);

    const uint32_t IOCON_INDEX_PIO0_18_config = (/* No addition pin function */
                                                 IOCON_PIO_MODE_INACT |
                                                 /* Enable hysteresis */
                                                 IOCON_PIO_HYS_EN |
                                                 /* Input not invert */
                                                 IOCON_PIO_INV_DI |
                                                 /* Disables Open-drain function */
                                                 IOCON_PIO_OD_DI |
                                                 /* Bypass input filter */
                                                 IOCON_PIO_SMODE_BYPASS |
                                                 /* IOCONCLKDIV0 */
                                                 IOCON_PIO_CLKDIV0);
    /* PIO0 PIN18 (coords: 61) is configured as GPIO, PIO0, 18. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_18, IOCON_INDEX_PIO0_18_config);

    const uint32_t ADC_LED_B = (/* No addition pin function */
                                IOCON_PIO_MODE_INACT |
                                /* Enable hysteresis */
                                IOCON_PIO_HYS_EN |
                                /* Input not invert */
                                IOCON_PIO_INV_DI |
                                /* Disables Open-drain function */
                                IOCON_PIO_OD_DI |
                                /* Bypass input filter */
                                IOCON_PIO_SMODE_BYPASS |
                                /* IOCONCLKDIV0 */
                                IOCON_PIO_CLKDIV0);
    /* PIO0 PIN23 (coords: 51) is configured as GPIO, PIO0, 23. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_23, ADC_LED_B);

    const uint32_t ADC_LED_G = (/* No addition pin function */
                                IOCON_PIO_MODE_INACT |
                                /* Enable hysteresis */
                                IOCON_PIO_HYS_EN |
                                /* Input not invert */
                                IOCON_PIO_INV_DI |
                                /* Disables Open-drain function */
                                IOCON_PIO_OD_DI |
                                /* Bypass input filter */
                                IOCON_PIO_SMODE_BYPASS |
                                /* IOCONCLKDIV0 */
                                IOCON_PIO_CLKDIV0);
    /* PIO0 PIN6 (coords: 46) is configured as GPIO, PIO0, 6. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_6, ADC_LED_G);

    /* ADC_CHN1 connect to P0_6 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN1, false);

    /* ADC_CHN2 connect to P0_14 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN2, false);

    /* ADC_CHN3 connect to P0_23 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN3, false);

    /* ADC_CHN8 connect to P0_18 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN8, false);

    /* ADC_CHN9 connect to P0_17 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN9, false);

    /* ADC_CHN10 connect to P0_13 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN10, false);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitI2CPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '17', peripheral: I2C0, signal: SCL, pin_signal: PIO0_10}
  - {pin_num: '16', peripheral: I2C0, signal: SDA, pin_signal: PIO0_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitI2CPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitI2CPins(void)
{
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);

    /* I2C0_SDA connect to P0_11 */
    SWM_SetMovablePinSelect(SWM0, kSWM_I2C0_SDA, kSWM_PortPin_P0_11);

    /* I2C0_SCL connect to P0_10 */
    SWM_SetMovablePinSelect(SWM0, kSWM_I2C0_SCL, kSWM_PortPin_P0_10);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDbgPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '60', peripheral: GPIO, signal: 'PIO0, 19', pin_signal: PIO0_19/ADC_7, direction: OUTPUT}
  - {pin_num: '58', peripheral: GPIO, signal: 'PIO0, 20', pin_signal: PIO0_20/ADC_6, direction: OUTPUT}
  - {pin_num: '57', peripheral: GPIO, signal: 'PIO0, 21', pin_signal: PIO0_21/ADC_5, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDbgPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitDbgPins(void)
{
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t DBG0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_19 (pin 60)  */
    GPIO_PinInit(BOARD_INITDBGPINS_DBG0_GPIO, BOARD_INITDBGPINS_DBG0_PORT, BOARD_INITDBGPINS_DBG0_PIN, &DBG0_config);

    gpio_pin_config_t DBG1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_20 (pin 58)  */
    GPIO_PinInit(BOARD_INITDBGPINS_DBG1_GPIO, BOARD_INITDBGPINS_DBG1_PORT, BOARD_INITDBGPINS_DBG1_PIN, &DBG1_config);

    gpio_pin_config_t DBG2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_21 (pin 57)  */
    GPIO_PinInit(BOARD_INITDBGPINS_DBG2_GPIO, BOARD_INITDBGPINS_DBG2_PORT, BOARD_INITDBGPINS_DBG2_PIN, &DBG2_config);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDALIPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '19', peripheral: FTM1, signal: 'CH, 1', pin_signal: PIO0_16, identifier: RX, direction: INPUT}
  - {pin_num: '30', peripheral: GPIO, signal: 'PIO0, 15', pin_signal: PIO0_15, identifier: TX, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDALIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitDALIPins(void)
{
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t TX_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_15 (pin 30)  */
    GPIO_PinInit(BOARD_INITDALIPINS_TX_GPIO, BOARD_INITDALIPINS_TX_PORT, BOARD_INITDALIPINS_TX_PIN, &TX_config);

    /* FTM1_CH1 connect to kSWM_FTM_Selection0 */
    SWM_SetFlextimerPinSelect(SWM0, kSWM_FTM1_CH1, kSWM_FTM_Selection0);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBTNPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: GPIO, signal: 'PIO0, 4', pin_signal: PIO0_4/ADC_11, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBTNPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitBTNPins(void)
{
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t BTN_USR_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_4 (pin 6)  */
    GPIO_PinInit(BOARD_INITBTNPINS_BTN_USR_GPIO, BOARD_INITBTNPINS_BTN_USR_PORT, BOARD_INITBTNPINS_BTN_USR_PIN, &BTN_USR_config);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
