/*
* Copyright 2023 NXP
* All rights reserved.
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDbgUARTPins(void); /* Function assigned for the Cortex-M0P */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSYSPins(void); /* Function assigned for the Cortex-M0P */

/*! @name PIO1_1 (number 18), LED_B_P
  @{ */
#define BOARD_INITLEDPINS_LED_B_P_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_LED_B_P_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_B_P_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_2 (number 20), LED_B_N
  @{ */
#define BOARD_INITLEDPINS_LED_B_N_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_LED_B_N_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_B_N_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_3 (number 29), LED_R_P
  @{ */
#define BOARD_INITLEDPINS_LED_R_P_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_LED_R_P_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_R_P_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_4 (number 31), LED_R_N
  @{ */
#define BOARD_INITLEDPINS_LED_R_N_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_LED_R_N_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_R_N_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_5 (number 35), LED_G_P
  @{ */
#define BOARD_INITLEDPINS_LED_G_P_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_LED_G_P_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_G_P_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_6 (number 38), LED_G_N
  @{ */
#define BOARD_INITLEDPINS_LED_G_N_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_LED_G_N_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_LED_G_N_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDPins(void); /* Function assigned for the Cortex-M0P */

#define IOCON_PIO_CLKDIV0 0x00u      /*!<@brief IOCONCLKDIV0 */
#define IOCON_PIO_HYS_EN 0x20u       /*!<@brief Enable hysteresis */
#define IOCON_PIO_INV_DI 0x00u       /*!<@brief Input not invert */
#define IOCON_PIO_MODE_INACT 0x00u   /*!<@brief No addition pin function */
#define IOCON_PIO_OD_DI 0x00u        /*!<@brief Disables Open-drain function */
#define IOCON_PIO_SMODE_BYPASS 0x00u /*!<@brief Bypass input filter */

/*! @name PIO1_1 (number 18), LED_B_P
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDPINS_DEINIT_LED_B_P_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_DEINIT_LED_B_P_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDPINS_DEINIT_LED_B_P_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_DEINIT_LED_B_P_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_DEINIT_LED_B_P_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PIO1_2 (number 20), LED_B_N
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDPINS_DEINIT_LED_B_N_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_DEINIT_LED_B_N_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDPINS_DEINIT_LED_B_N_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_DEINIT_LED_B_N_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_DEINIT_LED_B_N_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PIO1_3 (number 29), LED_R_P
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDPINS_DEINIT_LED_R_P_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_DEINIT_LED_R_P_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDPINS_DEINIT_LED_R_P_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_DEINIT_LED_R_P_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_DEINIT_LED_R_P_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PIO1_4 (number 31), LED_R_N
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDPINS_DEINIT_LED_R_N_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_DEINIT_LED_R_N_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDPINS_DEINIT_LED_R_N_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_DEINIT_LED_R_N_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_DEINIT_LED_R_N_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PIO1_5 (number 35), LED_G_P
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDPINS_DEINIT_LED_G_P_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_DEINIT_LED_G_P_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDPINS_DEINIT_LED_G_P_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_DEINIT_LED_G_P_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_DEINIT_LED_G_P_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PIO1_6 (number 38), LED_G_N
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDPINS_DEINIT_LED_G_N_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDPINS_DEINIT_LED_G_N_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define BOARD_INITLEDPINS_DEINIT_LED_G_N_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITLEDPINS_DEINIT_LED_G_N_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDPINS_DEINIT_LED_G_N_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*!
 * @brief This is a de-initialization function for 'BOARD_InitLEDPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BOARD_InitLEDPins_deinit(void); /* Function assigned for the Cortex-M0P */

/*! @name ADC_9 (number 63), ADC_NTC
  @{ */
#define BOARD_INITADCPINS_ADC_NTC_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_ADC_NTC_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_ADC_NTC_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name ADC_2 (number 49), ADC_LED_R
  @{ */
#define BOARD_INITADCPINS_ADC_LED_R_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_ADC_LED_R_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_ADC_LED_R_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name ADC_1 (number 46), ADC_LED_G
  @{ */
#define BOARD_INITADCPINS_ADC_LED_G_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_ADC_LED_G_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_ADC_LED_G_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name ADC_3 (number 51), ADC_LED_B
  @{ */
#define BOARD_INITADCPINS_ADC_LED_B_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_ADC_LED_B_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_ADC_LED_B_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name ADC_10 (number 2), ADC_POT
  @{ */
#define BOARD_INITADCPINS_ADC_POT_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_ADC_POT_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_ADC_POT_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name ADC_8 (number 61), ADC_ALS
  @{ */
#define BOARD_INITADCPINS_ADC_ALS_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_ADC_ALS_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_ADC_ALS_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitADCPins(void); /* Function assigned for the Cortex-M0P */

#define IOCON_PIO_CLKDIV0 0x00u      /*!<@brief IOCONCLKDIV0 */
#define IOCON_PIO_HYS_EN 0x20u       /*!<@brief Enable hysteresis */
#define IOCON_PIO_INV_DI 0x00u       /*!<@brief Input not invert */
#define IOCON_PIO_MODE_INACT 0x00u   /*!<@brief No addition pin function */
#define IOCON_PIO_OD_DI 0x00u        /*!<@brief Disables Open-drain function */
#define IOCON_PIO_SMODE_BYPASS 0x00u /*!<@brief Bypass input filter */

/*! @name PIO0_17 (number 63), ADC_NTC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITADCPINS_DEINIT_ADC_NTC_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITADCPINS_DEINIT_ADC_NTC_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define BOARD_INITADCPINS_DEINIT_ADC_NTC_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_DEINIT_ADC_NTC_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_DEINIT_ADC_NTC_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PIO0_14 (number 49), ADC_LED_R
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_R_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_R_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_R_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_R_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_R_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name PIO0_6 (number 46), ADC_LED_G
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_G_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_G_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_G_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_G_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_G_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PIO0_23 (number 51), ADC_LED_B
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_B_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_B_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_B_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_B_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_DEINIT_ADC_LED_B_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name PIO0_13 (number 2), ADC_POT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITADCPINS_DEINIT_ADC_POT_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITADCPINS_DEINIT_ADC_POT_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define BOARD_INITADCPINS_DEINIT_ADC_POT_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITADCPINS_DEINIT_ADC_POT_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITADCPINS_DEINIT_ADC_POT_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*!
 * @brief This is a de-initialization function for 'BOARD_InitADCPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BOARD_InitADCPins_deinit(void); /* Function assigned for the Cortex-M0P */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2CPins(void); /* Function assigned for the Cortex-M0P */

/*! @name PIO0_19 (number 60), DBG0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDBGPINS_DBG0_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDBGPINS_DBG0_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_INITDBGPINS_DBG0_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITDBGPINS_DBG0_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITDBGPINS_DBG0_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_20 (number 58), DBG1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDBGPINS_DBG1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDBGPINS_DBG1_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */
#define BOARD_INITDBGPINS_DBG1_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITDBGPINS_DBG1_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITDBGPINS_DBG1_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_21 (number 57), DBG2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDBGPINS_DBG2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDBGPINS_DBG2_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */
#define BOARD_INITDBGPINS_DBG2_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITDBGPINS_DBG2_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITDBGPINS_DBG2_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDbgPins(void); /* Function assigned for the Cortex-M0P */

/*! @name PIO0_16 (number 19), RX
  @{ */
#define BOARD_INITDALIPINS_RX_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITDALIPINS_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITDALIPINS_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_15 (number 30), TX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDALIPINS_TX_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDALIPINS_TX_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */
#define BOARD_INITDALIPINS_TX_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITDALIPINS_TX_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITDALIPINS_TX_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDALIPins(void); /* Function assigned for the Cortex-M0P */

/*! @name PIO0_4 (number 6), BTN_USR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBTNPINS_BTN_USR_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBTNPINS_BTN_USR_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define BOARD_INITBTNPINS_BTN_USR_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITBTNPINS_BTN_USR_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITBTNPINS_BTN_USR_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBTNPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
